#!/bin/sh

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS="$*"

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/postrm.d && run-parts --arg="3.16.3-parrot-amd64" --arg="/boot/vmlinuz-3.16.3-parrot-amd64" /etc/kernel/postrm.d
exit 0
